[package]
name = "cmdo"
version = "0.1.0"
edition = "2021"

[dependencies]
async-openai = "0.23.4"
clap = { version = "4.5.9", features = ["derive"] }
copypasta = "0.10.1"
tokio = { version= "1.38.1", features = ["full", "rt-multi-thread"] }
